   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: scaletestapp
     labels:
       app: scaletestapp
   spec:
     selector:
       matchLabels:
         app: scaletestapp
     template:
       metadata:
         labels:
           app: scaletestapp
       spec:
         containers:
          - name: scaletestapp
            image: shestera/scaletestapp:latest
            ports:
            - containerPort: 8080
            resources:
              requests:
                memory: "32Mi"
              limits:
                memory: "64Mi"